### ISSUE TITLE
Icon not showing on fresh Fedora 32 Workstation install

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/com.github.tchx84.Flatseal#17]
![Screenshot from 2020-07-18 15-13-25](https://user-images.githubusercontent.com/62922522/87861174-59668100-c909-11ea-98a6-ffedba0026ac.png)

The flathub repo is installed on the system level.  Let me know if you need more information from me.

**Comment by uncivilgentleman** [comment]
Whelp I reinstalled Fedora (for different reasons) and this time the icon for Flatseal is showing.

**Comment by meisme-dev** [comment]
i have the same issue (fedora silverblue 36)
edit: fixed it by deleting ~/.local/share/icons/hicolor/scalable/apps/com.github.tchx84.Flatseal.svg and reinstalling flatseal
