### ISSUE TITLE
CJK glyphs rendering as "glyph not found" ("tofu") characters

### ISSUE THREAD

**Issue by ssokolow** [flathub/com.github.tchx84.Flatseal#42]
A string of CJK characters like [文字化け](https://en.wikipedia.org/wiki/Mojibake) renders as four blank rectangles will render as ["tofu" characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)). (i.e. Windows-style empty rectangle renderings of the `.notdef` glyph) if pasted/typed/etc. into one of the text-entry fields like "Other files".

I can see this being a significant problem for people who habitually name folders using non-latin scripts.

Apparently Flatseal is missing some fonts or font settings that are present in the AntiMicroX, Arduino IDE, Blender, Firefox, FocusWriter, Godot, JDownloader, KCachegrind, Krita, LMMS, MEGAsync, Okteta, Sweet Home 3D, Thunderbird, Tor Browser, and Ungoogled Chromium flatpaks... though Bustle, Deluge, HandBrake, Inkscape, and jstest-gtk *do* have the same problem as of my opening this bug. (I've reported bugs for some of them, but not all... since cases like jstest-gtk were a struggle just to *find* a text-entry field to test with.)

Hopefully that list of "works here" and "doesn't work here" will help you narrow down the cause.

**Comment by tchx84** [comment]
This is widespread issue with many flatpak application, see https://github.com/tchx84/Flatseal/issues/501
