### ISSUE TITLE
Changing any of the permission shows a triangle warning issue

### ISSUE THREAD

**Issue by amtm2000** [flathub/com.github.tchx84.Flatseal#47]
So anytime I toggle any of the permissions on Flatseal, there seems to appear a triangle warning icon beside the toggle icon. I exit the application, I then restart, none of the permission I toggle applied. Basically, I can't seem to use the application to change permission on any flatpak application. 

I'm running Pop_Os 22.04 on a virtual machine with Windows 10 as the host OS.

**Comment by tchx84** [comment]
Two things:
1. That alert sign only means that you modified that permission, that's all.
2. Can't really tell why the changes aren't saved, maybe you can provide more information about how you're running Flatseal?

I am closing this, please create a issue on the upstream issue tracker https://github.com/tchx84/Flatseal/issues
