### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by VictorVow** [flathub/com.github.tchx84.Flatseal#53]
Flathub allows changelogs for each new release - can these be automated?

**Comment by Francewhoa** [comment]
Hello @Victor239 :) This is a great idea

It seems this is already done within the Flatseal's upstream repository at https://github.com/tchx84/Flatseal/blob/master/CHANGELOG.md

I found the link above at https://flathub.org/fr/apps/com.github.tchx84.Flatseal 
Under the "Link" horizontal tab.

If you're not familiar with the Flathub upstream repositories, for each Flatpak package, the link to their upstream repository can be found under this same "Link" horizontal tab for each package at https://flathub.org

**Comment by VictorVow** [comment]
Looked into it more and found out that changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by tchx84** [comment]
ops, I don't check this repository too often (hence the README). If you still think this is important please open an issue upstream.
